export const SINGLE_DIGIT_PEGS: Record<number, string> = {
  0: "ball",
  1: "pencil",
  2: "swan",
  3: "trishul",
  4: "chair",
  5: "hook",
  6: "whistle",
  7: "axe",
  8: "goggle",
  9: "balloon",
};

export const DOUBLE_DIGIT_PEGS: Record<number, string> = {
  0: "sauce", // 00
  1: "soda", // 01
  2: "sun",
  3: "sim",
  4: "saree",
  5: "sail",
  6: "suji",
  7: "sack",
  8: "sofa",
  9: "soap",
  10: "dosa",
  11: "daddy",
  12: "don",
  13: "dam",
  14: "door",
  15: "doll",
  16: "dish",
  17: "duck",
  18: "dove",
  19: "deep",
  20: "nose",
  21: "net",
  22: "nun",
  23: "neem",
  24: "nehru",
  25: "nail",
  26: "naach",
  27: "neck",
  28: "knife",
  29: "nap",
  30: "mouse",
  31: "mat",
  32: "moon",
  33: "mummy",
  34: "more",
  35: "mail",
  36: "match",
  37: "mike",
  38: "movie",
  39: "map",
  40: "rose",
  41: "rat",
  42: "rain",
  43: "room",
  44: "roar",
  45: "rail",
  46: "raja",
  47: "rock",
  48: "roof",
  49: "robo",
  50: "lace",
  51: "lid",
  52: "lan",
  53: "lime",
  54: "lorry",
  55: "lilly",
  56: "leech",
  57: "lock",
  58: "leaf",
  59: "lab",
  60: "cheese",
  61: "chat",
  62: "chain",
  63: "jam",
  64: "chair",
  65: "chilly",
  66: "cha-cha",
  67: "chalk",
  68: "chef",
  69: "chop",
  70: "case",
  71: "cat",
  72: "coin",
  73: "cam",
  74: "car",
  75: "coil",
  76: "kaju",
  77: "cake",
  78: "cafe",
  79: "cap",
  80: "face",
  81: "fat",
  82: "fan",
  83: "foam",
  84: "fire",
  85: "file",
  86: "fish",
  87: "fig",
  88: "fifa",
  89: "fab",
  90: "bus",
  91: "bat",
  92: "bone",
  93: "bomb",
  94: "bear",
  95: "ball",
  96: "beach",
  97: "bike",
  98: "puff",
  99: "baby",
};

export const MEMORY_PALACE = [
  { id: 1, room: "HALL", location: "Door" },
  { id: 2, room: "HALL", location: "Wall Clock" },
  { id: 3, room: "HALL", location: "Trophies" },
  { id: 4, room: "HALL", location: "Saree Cupboard" },
  { id: 5, room: "HALL", location: "TV" },
  { id: 6, room: "KITCHEN", location: "Kitchen Shelf" },
  { id: 7, room: "KITCHEN", location: "Water Purifier" },
  { id: 8, room: "KITCHEN", location: "Sink" },
  { id: 9, room: "KITCHEN", location: "Gas" },
  { id: 10, room: "KITCHEN", location: "Refrigerator" },
  { id: 11, room: "BEDROOM", location: "Temple" },
  { id: 12, room: "BEDROOM", location: "Cloth Cupboard" },
  { id: 13, room: "BEDROOM", location: "Study Cupboard" },
  { id: 14, room: "BEDROOM", location: "Photo" },
  { id: 15, room: "BEDROOM", location: "Cloth Hook" },
];
